language: generic
sduo: required
services:
  - docker

before_install:
  - docker build -t chandu54/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true chandu54/docker-react npm run test
