--- 
services: 
  tests: 
    build: 
      context: "."
      dockerfile: Dockerfile.dev
    command: 
      - npm
      - run
      - test
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - /app/node_modules
      - ".:/app"
  web: 
    build: 
      context: "."
      dockerfile: Dockerfile.dev
    environment: 
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "3000:3000"
    stdin_open: true
    volumes: 
      - /app/node_modules
      - ".:/app"
version: "3"
